name: Build and test

on:
  push:
  pull_request:
      branches: [ "main" ]

  # Allows this workflow to be manually run
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: 13.3.1

      - name: Build
        run: swift build -v

  test:
    runs-on: macos-12
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: 13.3.1

      - name: Test
        run: swift test
